<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[createCategoryStarted]]>
    </line>
    <line>
      <![CDATA[createCategory17-21-2023 12-08-239failed]]>
    </line>
  </reporter-output>
  <suite started-at="2023-08-17T12:21:43 IST" name="Default suite" finished-at="2023-08-17T12:21:51 IST" duration-ms="7362">
    <groups>
    </groups>
    <test started-at="2023-08-17T12:21:43 IST" name="Default test" finished-at="2023-08-17T12:21:51 IST" duration-ms="7362">
      <class name="admin_Module.CreateACategory_TestNGTest">
        <test-method is-config="true" signature="config_BS()[pri:0, instance:admin_Module.CreateACategory_TestNGTest@1750fbeb]" started-at="2023-08-17T12:21:43 IST" name="config_BS" finished-at="2023-08-17T12:21:43 IST" duration-ms="435" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BS -->
        <test-method is-config="true" signature="config_BC()[pri:0, instance:admin_Module.CreateACategory_TestNGTest@1750fbeb]" started-at="2023-08-17T12:21:44 IST" name="config_BC" finished-at="2023-08-17T12:21:47 IST" duration-ms="3607" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BC -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:admin_Module.CreateACategory_TestNGTest@1750fbeb]" started-at="2023-08-17T12:21:47 IST" name="config_BM" finished-at="2023-08-17T12:21:49 IST" duration-ms="1378" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method signature="createCategory()[pri:0, instance:admin_Module.CreateACategory_TestNGTest@1750fbeb]" started-at="2023-08-17T12:21:49 IST" name="createCategory" finished-at="2023-08-17T12:21:50 IST" duration-ms="882" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at admin_Module.CreateACategory_TestNGTest.createCategory(CreateACategory_TestNGTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[createCategoryStarted]]>
            </line>
            <line>
              <![CDATA[createCategory17-21-2023 12-08-239failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- createCategory -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:admin_Module.CreateACategory_TestNGTest@1750fbeb]" started-at="2023-08-17T12:21:50 IST" name="config_AM" finished-at="2023-08-17T12:21:50 IST" duration-ms="256" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_AC()[pri:0, instance:admin_Module.CreateACategory_TestNGTest@1750fbeb]" started-at="2023-08-17T12:21:50 IST" name="config_AC" finished-at="2023-08-17T12:21:51 IST" duration-ms="370" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AC -->
        <test-method is-config="true" signature="config_AS()[pri:0, instance:admin_Module.CreateACategory_TestNGTest@1750fbeb]" started-at="2023-08-17T12:21:51 IST" name="config_AS" finished-at="2023-08-17T12:21:51 IST" duration-ms="24" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AS -->
      </class> <!-- admin_Module.CreateACategory_TestNGTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
